/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current EUR exchange rates
         * @description Proxies Frankfurter API with 24h edge caching. Returns EUR-based rates for KRW, USD, JPY, CNY.
         */
        get: operations["getExchangeRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect text in an image via Google Cloud Vision
         * @description Sends a base64-encoded image to Google Cloud Vision TEXT_DETECTION and returns extracted text.
         */
        post: operations["ocrImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google OAuth flow */
        get: operations["googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out current user */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all trips for current user
         * @description Returns trip metadata (id, name, dates, emoji) without full JSONB data.
         */
        get: operations["listTrips"];
        put?: never;
        /** Create a new trip */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{tripId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single trip
         * @description Returns the full Trip object including all days, activities, and expenses.
         */
        get: operations["getTrip"];
        /**
         * Update a trip
         * @description Replaces the entire Trip JSONB data.
         */
        put: operations["updateTrip"];
        post?: never;
        /** Delete a trip */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ExchangeRatesResponse: {
            /** @example EUR */
            base: string;
            /** @example 2026-02-17 */
            date: string;
            /**
             * @example {
             *       "KRW": 1450,
             *       "USD": 1.08,
             *       "JPY": 160,
             *       "CNY": 7.8
             *     }
             */
            rates: {
                [key: string]: number;
            };
        };
        ErrorResponse: {
            error: string;
        };
        VisionResponse: {
            /**
             * @description Detected text from the image
             * @example Receipt total: €25.50
             */
            text: string;
        };
        VisionRequest: {
            /**
             * @description Base64 encoded image (with or without data URL prefix)
             * @example data:image/jpeg;base64,...
             */
            image: string;
        };
        UserResponse: {
            user: {
                id: string;
                email: string;
                name: string | null;
            } | null;
        };
        LogoutResponse: {
            success: boolean;
        };
        TripListResponse: {
            trips: components["schemas"]["TripListItem"][];
        };
        TripListItem: {
            id: string;
            tripName: string;
            startDate: string;
            endDate: string;
            emoji?: string;
            createdAt: string;
            updatedAt: string;
        };
        TripResponse: {
            trip: components["schemas"]["Trip"];
        };
        Trip: {
            id: string;
            tripName: string;
            startDate: string;
            endDate: string;
            days: {
                id: string;
                dayNumber: number;
                date: string;
                destination: string;
                destinationId: string;
                activities: {
                    id: string;
                    contentId?: string;
                    name: string;
                    nameKo: string;
                    time: string;
                    duration: string;
                    /** @enum {string} */
                    type: "attraction" | "shopping" | "meal" | "transport" | "free";
                    estimatedCost: number;
                    currency: string;
                    isBooked: boolean;
                    isCompleted?: boolean;
                    isSkipped?: boolean;
                    booking?: {
                        confirmationNumber?: string;
                        voucherUrl?: string;
                        voucherFile?: string;
                        notes: string;
                        bookingDate?: string;
                        provider?: string;
                    };
                    lat?: number;
                    lng?: number;
                    memos?: string[];
                    expenses?: {
                        id: string;
                        amount: number;
                        currency: string;
                        description: string;
                        createdAt: string;
                        owner: string;
                    }[];
                    media?: {
                        id: string;
                        /** @enum {string} */
                        type: "image" | "video";
                        dataUrl: string;
                        thumbnail?: string;
                        caption?: string;
                        createdAt: string;
                    }[];
                }[];
                notes: string;
                flights?: {
                    id: string;
                    airline: string;
                    flightNumber: string;
                    departure: string;
                    arrival: string;
                    departureTime: string;
                    arrivalTime: string;
                    confirmationNumber?: string;
                    notes?: string;
                }[];
                accommodation?: {
                    id: string;
                    name: string;
                    address: string;
                    checkIn?: string;
                    checkOut?: string;
                    confirmationNumber?: string;
                    cost: number;
                    currency: string;
                    notes?: string;
                    lat?: number;
                    lng?: number;
                };
            }[];
            currentDayIndex: number;
            totalBudget: number;
            expenses: {
                id: string;
                dayId?: string;
                /** @enum {string} */
                category: "accommodation" | "food" | "transport" | "attraction" | "shopping" | "entertainment" | "other";
                amount: number;
                /** @enum {string} */
                currency: "EUR";
                description: string;
                date: string;
                owner: string;
            }[];
            restaurantComments: {
                id: string;
                restaurantId: string;
                text: string;
                rating?: number;
                date: string;
            }[];
            customDestinations: {
                id: string;
                name: string;
                nameKo: string;
                lat: number;
                lng: number;
                timezone: string;
                description: string;
                tips: string[];
                phrases: {
                    situation: string;
                    spanish: string;
                    pronunciation: string;
                    korean: string;
                }[];
                restaurants: {
                    id: string;
                    name: string;
                    cuisine: string;
                    priceRange: string;
                    rating: number;
                    address: string;
                    description: string;
                    mustTry: string[];
                    lat: number;
                    lng: number;
                }[];
                contents: {
                    id: string;
                    name: string;
                    nameKo: string;
                    /** @enum {string} */
                    type: "attraction" | "shopping" | "meal" | "transport" | "free";
                    description: string;
                    estimatedCost: number;
                    currency: string;
                    duration: string;
                    address: string;
                    lat: number;
                    lng: number;
                    imageUrl?: string;
                    tips?: string[];
                }[];
                transportation: {
                    from: string;
                    to: string;
                    /** @enum {string} */
                    type: "train" | "bus" | "taxi" | "rental_car" | "walk" | "metro";
                    duration: string;
                    estimatedCost: number;
                    currency: string;
                    notes: string;
                    bookingUrl?: string;
                }[];
                weatherInfo: {
                    avgTempHigh: number;
                    avgTempLow: number;
                    rainfall: string;
                    description: string;
                    clothing: string;
                };
            }[];
            immigrationSchedules: {
                id: string;
                /** @enum {string} */
                type: "departure" | "arrival";
                date: string;
                time: string;
                airport: string;
                airline?: string;
                flightNumber?: string;
                terminal?: string;
                gate?: string;
                confirmationNumber?: string;
                notes?: string;
            }[];
            interCityTransports: {
                id: string;
                fromDayId: string;
                toDayId: string;
                /** @enum {string} */
                type: "train" | "bus" | "taxi" | "rental_car" | "flight";
                departure?: string;
                arrival?: string;
                departureTime?: string;
                arrivalTime?: string;
                operator?: string;
                confirmationNumber?: string;
                estimatedCost?: number;
                currency?: string;
                notes?: string;
            }[];
            owners: {
                id: string;
                name: string;
                color: string;
            }[];
            pendingCameraExpense: {
                amount: number;
                currency: string;
            } | null;
            createdAt: string;
            updatedAt: string;
            emoji?: string;
        };
        DeleteResponse: {
            deleted: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getExchangeRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current exchange rates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRatesResponse"];
                };
            };
            /** @description Upstream Frankfurter API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Exchange rate service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ocrImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisionRequest"];
            };
        };
        responses: {
            /** @description Extracted text from image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisionResponse"];
                };
            };
            /** @description No image provided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Vision API not configured or processing error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Google Vision API request failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to app after login */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid callback */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    listTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of trips */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Trip"];
            };
        };
        responses: {
            /** @description Trip created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Trip"];
            };
        };
        responses: {
            /** @description Trip updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trip deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Trip not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
